### PR TITLE
Theming and style tweaks

### PR DESCRIPTION
**Pull request by conrad-vanl**
### What does this PR do, or why is it needed?

Numerous style tweaks, namely:

- expose theme values set in Rock on -api and integrate into content single and content card views
- create a new `ContentSeriesContentItem` view with series branding (used for sermon and devo series)
- weekend content item style tweaks
- remove imagery from children content feed
- remove redundant text on discovery screen tiles
- card style tweaks, including a new version of `FeaturedCard` just for NewSpring, to better respect NewSpring's imagery and brand. Uses the new card for any series, sermon, or devo that shows on the home feed.

Screen Shot 2019-11-14 at 11 58 33 PM
Screen Shot 2019-11-14 at 11 58 49 PM
Screen Shot 2019-11-14 at 11 59 05 PM
Screen Shot 2019-11-14 at 11 58 22 PM
Screen Shot 2019-11-14 at 11 58 13 PM
Screen Shot 2019-11-14 at 11 58 05 PM
Screen Shot 2019-11-15 at 12 00 36 AM

## TODO

- [ ] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [ ] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
@conrad-vanl 

Screenshot 2019-11-15 16 32 34

**Comment by conrad-vanl** [comment]
Another option to fix that in addition to what you did in your PR, would be to tweak shadows. We need to tweak shadows on core, but we also tweaked them for willow some as well: https://github.com/Differential/willow-prototype/blob/master/packages/WillowCreekApp/src/theme/theme.js#L122-L135

Long term Michael R. is working on new child content carousel card designs to better suit

**Comment by richarddubay** [comment]
I like how you've done the shadow tweaking. That's kind of dope. As we show MM what's what, I'll definitely keep that part in mind.

**Review by richarddubay — APPROVED** [review]

**Comment by richarddubay** [comment]
@redreceipt You've probably been following along, but I wanted to make you aware of these changes just in case. Frank and I showed them to MM earlier today and he approved. I approved the PR but wanted to get your eyes on it in case there was anything from your perspective that you thought needed to be changed.

**Comment by redreceipt** [comment]
I have not been following along. I have only simply 10,000 emails about this PR. @conrad-vanl just make a bunch of design improvements?

**Comment by richarddubay** [comment]
@redreceipt Yep. So that we don't have to update all the images for all the sermon series and studies forever.

**Pull request merged**
