### PR TITLE
[DEV-3748] Fixes Spacing on Prayer Tab

### PR DESCRIPTION
**Pull request by cdanwards**
## DESCRIPTION

This PR corrects the height of the prayer tab for larger screens.

### What does this PR do, or why is it needed?

Prayer-Space

This PR add padding to the bottom of the `TabView` in the Prayer Tab so that it fills down to the top of the `TabBarNavigator` at the bottom of the view.

### How do I test this PR?

Fire up the sim on an iPhone X and go to the prayer tab to see there's no negative space.

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [DEV-3748](https://newspring.atlassian.net/secure/RapidBoard.jspa?rapidView=71&modal=detail&selectedIssue=DEV-3748)
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [ ] Set two relevant reviewers

## REVIEW

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
I don't think really fixes the issue, it needs to go full screen. When some phone comes out that has an even bigger screen, you're just going to have to increase the padding. this is the problem:

Screen Shot 2019-05-06 at 1 50 34 PM

**Review by redreceipt — DISMISSED** [review]
I don't think really fixes the issue, it needs to go full screen. When some phone comes out that has an even bigger screen, you're just going to have to increase the padding. this is the problem:

Screen Shot 2019-05-06 at 1 50 34 PM

**Comment by cdanwards** [comment]
@redreceipt I'm not a big fan of just adding some padding to the bottom, however I was unable to find another way of getting the container to fill the whole space. `Flex: 1` didn't behave as you might expect on the `SafeAreaView` that wraps this whole view. That ideally should fix it, but it still had that gap.

**Comment by cdanwards** [comment]
@richarddubay @IsaacHardy Any thoughts?

**Comment by richarddubay** [comment]
@cdanwards Not off the top of my head. Maybe something with Dimensions and the window height? I know there is already some stuff in there about that. I can look closer if I need to.

**Comment by IsaacHardy** [comment]
That sliver at the bottom, which component is it? Could we change its color to match the rest?

**Comment by cdanwards** [comment]
@IsaacHardy so far as I can tell, it's just space between the `bottomTabNavigator` and the `SafeAreaView` of the Prayer index. I can't find where it is.

**Review by richarddubay — APPROVED** [review]
This looks like it works to me. Let's go!

**Pull request merged**
