### PR TITLE
[DEV-3702] Move My Prayer Content

### PR DESCRIPTION
**Pull request by richarddubay**
### What does this PR do, or why is it needed?
This PR moves the "My Prayers" content from the Connect tab to the My Prayers menu item on the prayer feature menu.

### How do I test this PR?
Fire up the app, go the prayer tab, scroll over to My Prayers and tap on that menu item. If you're signed in, your prayers should display. 
Screenshot 2019-04-17 11 40 04

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [DEV-3702](https://newspring.atlassian.net/browse/DEV-3702)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set two relevant reviewers

## REVIEW

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by IsaacHardy** [comment]
@richarddubay I'd like to hijack this PR to add some formatting to the list

**Comment by richarddubay** [comment]
@IsaacHardy Will you check on how I added the `<UserPrayerList />` component please? I'm not sure that's the best way to do that, but I'm also not sure where else to put that.

**Comment by IsaacHardy** [comment]
@richarddubay Ready for review again!

**Review by IsaacHardy — APPROVED** [review]
Best PR I've ever seen.

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
