### PR TITLE
App Clean Up

### PR DESCRIPTION
**Pull request by richarddubay**
### What does this PR do, or why is it needed?
This PR:

- Customized the Prayer Preview Cards and updated styles
- Updated Add Prayer Card styles
- Updated Prayer Menu styles
- Updated the Connect page so that all menu items point to the correct place. Note: the "Open Testing Panel" should no longer show in production.
- Updated all `@apollosproject` packages to `0.8.3` (which had the added bonus of fixing the warnings on the Add Prayer Form.
- Updated User Prayer Card styles.
- Disabled swiping on the tab view until we can figure out how to get the tabs and the menu to move in sync.
- 

### How do I test this PR?
Run through the prayer module and make note of any weird styling issues you might see.
Make sure that the items on the Connect tab go to the correct places.

---
> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [n/a] Closes [DEV-XXX](#url)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set two relevant reviewers

## REVIEW

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by IsaacHardy** [comment]
@richarddubay The "Start Praying" button is no longer working in this PR

**Comment by IsaacHardy** [comment]
@richarddubay It works, but only the bottom 5% of the button lol

**Comment by cdanwards** [comment]
@richarddubay @IsaacHardy I'm not having that problem with the `Start Praying` Button.

**Comment by redreceipt** [comment]
works for me too

**Review by cdanwards — APPROVED** [review]
Tested and poked around some. Found an issue unrelated to this PR and created an issue in JIRA. What this PR does LGTM!

**Pull request merged**
