### PR TITLE
(DEV-127) [API] Get prayer requests by group

### PR DESCRIPTION
**Pull request by IsaacHardy**
### What does this PR do, or why is it needed?
Gets a list of prayer requests from a user's community group members, serving team members, and family.

### What design trade-offs/decisions were made?
n.a.

### How do I test this PR?
1. Start up the server
2. Set `Authorization` token in header
3. Run the following query:
```
# Write your query or mutation here
query {
  getPrayerRequestsByGroups {
    id
    campusId
    text
    firstName
    lastName
    requestedByPersonAliasId
    createdByPersonAliasId
    isPublic
    flagCount
    categoryId
  }
}
```
## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
@IsaacHardy getting a 404

Screen Shot 2019-03-14 at 2 38 45 PM

**Comment by IsaacHardy** [comment]
@redreceipt I should have placed this in the pr, but you'll need to run it with the apollosrock env variables.

**Comment by IsaacHardy** [comment]
@redreceipt @richarddubay @cdanwards I'm still needing a review.

**Comment by richarddubay** [comment]
@IsaacHardy The name that Nick suggested for the Prayer Request endpoint is `GetForGroupMembersOfPersonInGroupTypes`, so that's what I went with. That will need to be updated in this PR. 

Also, the parameters are different now. You no longer need to pass in the Person Id. The list of group type ids is still a thing as well as a new boolean named `excludePerson`. If you don't want to have the logged-in persons prayers included in the list of prayers returned you can set that to `true`. This makes the endpoint generic enough that there doesn't need to be a second endpoint to include the logged-in persons prayers.

**Comment by IsaacHardy** [comment]
@richarddubay Endpoint has been updated. Could you confirm it is correct?

**Comment by richarddubay** [comment]
@IsaacHardy That looks correct. Are you okay with merging my other PR into `alpha-rock` so that this PR will work?

**Comment by redreceipt** [comment]
blocked by newspring/rock#827

**Comment by IsaacHardy** [comment]
@richarddubay @cdanwards This should no longer be block and is ready for review.

**Comment by redreceipt** [comment]
@IsaacHardy not working for me, I have one in there from Amber that's not showing up

Screen Shot 2019-03-28 at 1 08 33 PM

shows up in all requests

Screen Shot 2019-03-28 at 1 09 23 PM

made by amber

Screen Shot 2019-03-28 at 1 09 39 PM

and I know i'm logged in

Screen Shot 2019-03-28 at 1 16 08 PM

**Comment by redreceipt** [comment]
@IsaacHardy also `yarn start` isn't working...

```
~/Documents/Projects/ApollosProject (getPrayerRequestsByGroup) $ yarn start
yarn run v1.13.0
$ if test "$NOW_ENV" = "true" ; then yarn start:now ; else yarn start:dev ; fi
$ ./node_modules/.bin/lerna run start --parallel
lerna notice cli v3.4.3
lerna info Executing command in 2 packages: "yarn run start"
apollos-church-api: $ if test "$NOW_ENV" = "true" ; then yarn start:now ; else yarn start:dev ; fi
apolloschurchapp: $ babel-node ./scripts/get-introspection-data.js
apollos-church-api: $ nodemon ./src/index.js --exec babel-node --delay 2
apollos-church-api: [nodemon] 1.18.7
apollos-church-api: [nodemon] to restart at any time, enter `rs`
apollos-church-api: [nodemon] watching: *.*
apollos-church-api: [nodemon] starting `babel-node ./src/index.js`
apolloschurchapp: Error writing fragmentTypes (-api probably hasn't started yet). Trying again after wait. Attempt: 1 of 3
apollos-church-api: 🚀 Server ready at http://0.0.0.0:4000
apolloschurchapp: Error writing fragmentTypes (-api probably hasn't started yet). Trying again after wait. Attempt: 1 of 3
apolloschurchapp: Error writing fragmentTypes (-api probably hasn't started yet). Trying again after wait. Attempt: 1 of 3
apolloschurchapp: Error writing fragmentTypes (-api probably hasn't started yet). Trying again after wait. Attempt: 1 of 3
apolloschurchapp: Error writing fragmentTypes (-api probably hasn't started yet). Trying again after wait. Attempt: 1 of 3
^C
```

**Comment by IsaacHardy** [comment]
@redreceipt Then other PR I have open fixes that

**Comment by redreceipt** [comment]
blocked by newspring/rock#828

**Comment by richarddubay** [comment]
Screenshot 2019-03-28 16 52 15

I'm getting results now.

**Review by richarddubay — DISMISSED** [review]
👍

**Review by redreceipt — DISMISSED** [review]
🤘

**Review by redreceipt — APPROVED** [review]
again

**Review by richarddubay — APPROVED** [review]

**Pull request merged**
