### PR TITLE
Upgrades to 8.1.2

### PR DESCRIPTION
**Pull request by IsaacHardy**
### What does this PR do, or why is it needed?
This PR updates our repo to version 8.1.2. This allows us to have sms login, onboarding, and content personalization.
### How do I test this PR?
1. yarn
2. yarn start
3. Make sure all new features are working as intended and make sure all old features still work.
---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [DEV-3705](https://newspring.atlassian.net/browse/DEV-3705)
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [x] Set two relevant reviewers

## REVIEW

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
@IsaacHardy Here are a few things I noticed just giving this a really quick once over.

1. No images whatsoever.
Screenshot 2019-04-22 16 44 57
Screenshot 2019-04-22 16 45 22

2. My logged in person has no name, campus, or picture. FWIW, when I logged out and back in again, it knew my phone number (so SMS login worked), but it wasn't able to pull any other information about me during the onboarding process. 
Screenshot 2019-04-22 16 45 46
Screenshot 2019-04-22 16 46 23

3. Devotionals did not have any scripture
Screenshot 2019-04-22 16 48 31

I think this is good for starters.

**Comment by IsaacHardy** [comment]
@richarddubay That's because this only upgrades the version. Not the data. That is what this PR does: https://github.com/NewSpring/ApollosProject/pull/6

**Comment by richarddubay** [comment]
@IsaacHardy Seems to me that there is no way to really test this then. I mean, it didn't crash, so is that considered a good test? We almost need to have this PR and #6 together in `master` before we can say that either of them actually work. Like we're going to have to _assume_ they both work, merge them, and then go back and fix any bugs we find later.

**Review by cdanwards — COMMENTED** [review]
The components included in this PR load in both Android and IOS. It's hard to test anything beyond that because of the lack of content to display. @IsaacHardy are we comfortable with that being the criteria to pass?

**Comment by IsaacHardy** [comment]
@cdanwards This is now ready to be reviewed.

**Review by redreceipt — APPROVED** [review]

**Review by cdanwards — APPROVED** [review]
Looks good! And the tests all passed.

**Pull request merged**
