### PR TITLE
(DEV-4079) Fixes Android Videos...really this time

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Allows `CLEARTEXT` in Android to Wistia

### How do I test this PR?

Download onto a real android device and try a video.

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
ok this one is ready to test and review

**Comment by richarddubay** [comment]
@redreceipt I was able to verify that I could run this on both the Android and iOS simulators, that they boot up, and that they play videos. I do get a RSOD error on iOS now, but it does not seem to hinder the video playback. I'm assuming you tested this on a device?

**Comment by redreceipt** [comment]
What is an RSOD? No I did not test on a real iOS device.

**Comment by richarddubay** [comment]
RSOD = Red Screen Of Death. You know, the big red error screen. But I could dismiss the error and the video was still playing.
And by "real device" I meant Android. I should have been more clear.

**Review by richarddubay — APPROVED** [review]

**Pull request merged**
