### PR TITLE
(DEV-3670) Fixes Storybook

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Fixes Storybook for us

### How do I test this PR?

`yarn storybook`

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [DEV-3670](https://newspring.atlassian.net/browse/DEV-3670)
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [x] Set two relevant reviewers

## REVIEW

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by IsaacHardy** [comment]
@redreceipt Receiving an error when I `yarn storybook`.
Screen Shot 2019-04-09 at 9 59 22 AM

**Comment by redreceipt** [comment]
Not sure, haven’t seen that one

—
Michael

**Comment by redreceipt** [comment]
@IsaacHardy not really sure how to debug your issue as I'm not getting an error on my end.

```
~/Documents/Projects/ApollosProject (fix-storybook) $ yarn storybook
yarn run v1.13.0
$ ./node_modules/.bin/lerna run storybook --stream --scope newspringchurchapp
lerna notice cli v3.13.1
lerna info filter [ 'newspringchurchapp' ]
lerna info Executing command in 1 package: "yarn run storybook"
newspringchurchapp: $ rnstl --searchDir ../ --pattern "apollos*/src/**/*.stories.js" && storybook start -p 7007  | react-native start --projectRoot $PWD/storybook
newspringchurchapp: 
newspringchurchapp: Generating Dynamic Storybook File List
newspringchurchapp:  
newspringchurchapp: Output file:       /Users/michael.neeley/Documents/Projects/ApollosProject/packages/newspringchurchapp/storybook/storyLoader.js
newspringchurchapp: Patterns:          ["/Users/michael.neeley/Documents/Projects/ApollosProject/packages/apollos*/src/**/*.stories.js"]
newspringchurchapp: Located 0 files matching pattern '/Users/michael.neeley/Documents/Projects/ApollosProject/packages/apollos*/src/**/*.stories.js' 
newspringchurchapp: Compiled story loader for 0 files:
newspringchurchapp:   
newspringchurchapp: ┌──────────────────────────────────────────────────────────────────────────────┐
newspringchurchapp: │                                                                              │
newspringchurchapp: │  Running Metro Bundler on port 8081.                                         │
newspringchurchapp: │                                                                              │
newspringchurchapp: │  Keep Metro running while developing on any JS projects. Feel free to        │
newspringchurchapp: │  close this tab and run your own Metro instance if you prefer.               │
newspringchurchapp: │                                                                              │
newspringchurchapp: │  https://github.com/facebook/react-native                                    │
newspringchurchapp: │                                                                              │
newspringchurchapp: └──────────────────────────────────────────────────────────────────────────────┘
newspringchurchapp: Looking for JS files in
newspringchurchapp:    /Users/michael.neeley/Documents/Projects/ApollosProject/packages/newspringchurchapp 
newspringchurchapp: Loading dependency graph, done.
```

**Review by cdanwards — APPROVED** [review]
Tested and looked through changes. LGTM!

**Review by richarddubay — APPROVED** [review]
If the point of this was that Storybook actually runs, then this passes! 👍

**Pull request merged**
