### PR TITLE
(DEV-3654) Adds Short Domain to Deep Link Functionality

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Allows apps to open short links.

### How do I test this PR?

Try to open a short link on iOS and Android like [ns.link/stories/emma-guthrie](https://ns.link/stories/emma-guthrie)

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
@redreceipt With this PR, do we need to make any changes to the `apple-app-site-association` file? My guess is no because the routes are the same (`/devotionals` for example), but I want to make sure.

**Comment by richarddubay** [comment]
Screenshot 2019-11-18 10 54 36

Also, it doesn't seem to want to open this link in the app. Am I missing something else?

**Comment by redreceipt** [comment]
uninstall the app and try again, the OS defaults for the app may be messed up

**Comment by richarddubay** [comment]
Okay, this seems to work on Android. I can't get an `ns.link` URL to stay in the messages app on the simulator. It just disappears. So I'll merge this and then test it on my device when I get the build.

**Review by richarddubay — APPROVED** [review]

**Pull request merged**
