### PR TITLE
(DEV-3697) Private Prayer Requests are able to be returned to that user.

### PR DESCRIPTION
**Pull request by IsaacHardy**
## DESCRIPTION
We needed to update the api call to ignore the `isPublic` flag and ignore it when creating a prayer.

### What does this PR do, or why is it needed?
This PR removes references to the `IsPublic` attribute and automatically sets it to True no matter what when creating from the app.

### How do I test this PR?
1. Login on the Graphql playground
2. Confirm which prayers are set to "IsPublic" in Alpha-Rock
3. Run this mutation query to create a new prayer:
```
mutation {
  addPublicPrayerRequest(FirstName: "Test", LastName: "Bro", Text: "Jesus Rocks", CampusId: 16, CategoryId: 1, IsAnonymous: "True") {
    id
    firstName
    lastName
    text
    requestedByPersonAliasId
    campusId
    categoryId
    flagCount
    prayerCount
    isAnonymous
    person {
      id
      firstName
      lastName
    }
  }
}
```
4. Confirm the newly created mutation has `IsPublic` set to true in Alpha-Rock.
5. Get all user prayer requests running this query:
```
query {
  getCurrentPersonPrayerRequests {
    id
    firstName
    lastName
    text
    enteredDateTime
  }
}
```
6. Confirm all user prayers are listed.
---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [DEV-3697](https://newspring.atlassian.net/browse/DEV-3697)
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [x] Set two relevant reviewers

## REVIEW

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by IsaacHardy** [comment]
This PR should be review AFTER https://github.com/NewSpring/ApollosProject/pull/13

**Comment by richarddubay** [comment]
@IsaacHardy I'm kind of at a loss on this one. Is it supposed to be able to return private prayer requests? I added a private one in `alpha-rock` but it isn't being pulled in my query. Also, it looks like we're pretty much hardcoding things to be public. Is it just the title of the PR that's confusing?

**Comment by redreceipt** [comment]
@richarddubay I think we changed to using beta rock in the config.yml but I could be wrong

**Comment by IsaacHardy** [comment]
@richarddubay Check the PR not that #13 is reviewed and merged. Let me know if there's any confusing now.

**Comment by IsaacHardy** [comment]
@richarddubay To make sure you are creating prayers correctly, the prayer MUST be PUBLIC, APPROVED, and ACTIVE. All prayer requests created through the APP will have those three attributes set to TRUE. 

A "Private" prayer request is a prayer request with the attribute value "IsAnonymous" set to "True".

**Comment by richarddubay** [comment]
@IsaacHardy What you have here did pull my "anonymous" prayer request, just not the one that I added through the Rock UI as "private". I think the wording of "private" threw me off. From an app perspective, no prayer being added can truly be "private", but it can be anonymous. 

@redreceipt I added you as a reviewer since Dan is now flying south for the spring. 🐦

Question: Should we be able to show a person a truly "private" prayer request that someone (a care team member perhaps) added through the Rock UI?

**Review by richarddubay — APPROVED** [review]

**Comment by IsaacHardy** [comment]
@richarddubay When you say "private" do you mean "not public"? Because there is no attribute titled, "private". 

With that being said, I think the current functionality works as intended for the app. We can discuss that use case when the time comes (closer to launch). The fix is easy but I rather not make that change until we are 100% confident in how this prayer feature will function within our prayer teams.

**Review by cdanwards — APPROVED** [review]
Tested and `isPublic` correctly was applied. LGTM!

**Pull request merged**
