### PR TITLE
Updated Bundle Id and App name

### PR DESCRIPTION
**Pull request by IsaacHardy**
### What does this PR do, or why is it needed?
This PR updates the bundle id and app name for the NewSpring iOS and Android versions of The Apollos Project. 

### How do I test this PR?
Check to see if both the android and iOS versions of the app run and have the name `newspringchurchapp`.
> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [#ISSUE]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [x] Set two relevant reviewers

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Review by richarddubay — APPROVED** [review]

**Comment by richarddubay** [comment]
I was able to run the app on both iOS and Android so I'm guessing this works for now. For the record, I could run `yarn ios` just fine, but there was a problem running `yarn android`. 

`Error: Activity class {com.newspringchurchapp/com.newspringchurchapp.MainActivity} does not exist.`

I was able to successfully run the app to the Android emulator from Android Studio though.

**Comment by redreceipt** [comment]
@richarddubay what you're referring to always happens, my Android PR in core fixes that.

**Comment by cdanwards** [comment]
The branch is working on IOS for me. But on Android I get 2 errors. The one I get when I sync the build gradle is the error about the `react-native-passkit-wallet` module. The other happens when I try to build and I get an error saying `Android resource linking failed` `error: failed processing manifest.`

**Comment by IsaacHardy** [comment]
@richarddubay Were you able to run on Android?

**Comment by richarddubay** [comment]
> @richarddubay Were you able to run on Android?

@IsaacHardy Yep. Once I added the `GOOGLE_MAPS_API_KEY` it worked for me.

**Comment by IsaacHardy** [comment]
@richarddubay Are you able to sync with @cdanwards to see why he is unable to run it?

**Review by cdanwards — APPROVED** [review]

**Pull request merged**
