### PR TITLE
(DEV-4142) Adds Forgot Password Link

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Adds forgot password link

### How do I test this PR?

Click it and reset your password!

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
won't actually work until core supports it

**Comment by redreceipt** [comment]
but the API can be tested

**Comment by redreceipt** [comment]
https://github.com/ApollosProject/apollos-prototype/pull/1152

**Comment by richarddubay** [comment]
@redreceipt This should no longer be blocked, right? I can go ahead and review it?

**Comment by redreceipt** [comment]
ready

**Comment by richarddubay** [comment]
Blocked on https://newspring.atlassian.net/browse/OPS-5905

**Review by richarddubay — APPROVED** [review]
This is good from our end.

**Pull request merged**
