### PR TITLE
[DEV-3956] Update Group Finder Link

### PR DESCRIPTION
**Pull request by richarddubay**
### What does this PR do, or why is it needed?
This PR updates the group finder link to point to our new group finder at https://newspring.cc/groups/finder

Screenshot 2019-09-04 13 13 45

### How do I test this PR?
In your sim, go to the Connect page, tap on the "Join a small group" link and it should take you to the new group finder in Safari.

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
going to the link in iOS makes the safari window cover a little bit of the nav bar at the bottom, I confirmed it's fine when getting there through safari

Screen Shot 2019-09-04 at 3 59 33 PM

Screen Shot 2019-09-04 at 4 00 26 PM

**Comment by richarddubay** [comment]
Do you think there is anything we can do about that? It's literally just a link out to Safari.

**Comment by redreceipt** [comment]
I was thinking it may the safari webview that we're using

**Comment by redreceipt** [comment]
either way, I guess it's not related to this PR but we should at least file an issue to understand the problem

**Review by redreceipt — APPROVED** [review]

**Comment by richarddubay** [comment]
@redreceipt I agree with creating an issue. I wonder if other parts of our site (or other sites) do the same thing if we link out to them?

**Pull request merged**
