### PR TITLE
[DEV-3828] v0.8.7

### PR DESCRIPTION
**Pull request by vinnyjth**
### How do I test this PR?

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [DEV-3828](https://newspring.atlassian.net/browse/DEV-3828)
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [ ] Set two relevant reviewers

## REVIEW

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
Screen Shot 2019-06-05 at 8 57 41 AM

**Comment by IsaacHardy** [comment]
@vinnyjth Currenting getting errors when trying to create the fragmentTypes. Any idea why that would be the case?

**Comment by IsaacHardy** [comment]
@vinnyjth Logging on errors here:
Simulator Screen Shot - iPhone X - 2019-06-05 at 10 56 47

Clicking the "X" does not close the modal.

**Comment by vinnyjth** [comment]
See if this commit fixes it: https://github.com/NewSpring/ApollosProject/pull/131/commits/9e1fb8cb92c29cf77781f4e77801eb3da32ac490

**Comment by IsaacHardy** [comment]
@vinnyjth Nope :(

**Comment by IsaacHardy** [comment]
It seems that most everything else is working as intended.

**Review by IsaacHardy — APPROVED** [review]

**Pull request merged**
