### PR TITLE
(DEV-3851) Adds "No Campus" Option

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-08-11 at 5 37 27 PM

### What does this PR do, or why is it needed?

Allows the user to specify online-only attendance, if they skip, they default to "web".

### How do I test this PR?

- [ ] test changing your campus to web via the link
- [ ] test changing your campus to web via the skip button. to remove your campus PATCH your family group `CampusId` to null

Screen Shot 2019-08-11 at 5 39 10 PM

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
let's hold off on this until I can make changes post-core update

**Review by cdanwards — COMMENTED** [review]
Skip worked, but when I selected `I attend Online` I started getting this error and now it red screens whenever I go to that onboarding screen.


Screen Shot 2019-08-20 at 1 23 33 PM

**Comment by redreceipt** [comment]
fixed

**Review by cdanwards — APPROVED** [review]
Looks good to me! Tested a lot of different use cases. Going through to press skip and the `I attend online` button. The only thing is that the campuses aren't showing up for me on the locationfinder. But that might be a different issue.

**Pull request merged**
