### PR TITLE
[DEV-4221] New Beta Release

### PR DESCRIPTION
**Pull request by richarddubay**
## TODO

- [ ] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [ ] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
@redreceipt I didn't up the version on this in an attempt to get it approved as quickly as possible. If you think we need to `bump`, let me know.

**Comment by redreceipt** [comment]
I feel like it just helps to ask people “What version are you on?” If they are having problems

—
Michael

**Comment by richarddubay** [comment]
I definitely don't disagree with you. Just wasn't sure we wanted to wait the 2 days to get this one out. That way MM and others could have the latest performance enhancements before they test on Wednesday. We can bump and hope that Apple approves before then if that's the best practice.

But if we're going to do that, I just need to do that now.

**Comment by redreceipt** [comment]
Last time it was fast, I say we always bump the version number for beta

—
Michael

**Comment by richarddubay** [comment]
That's probably a good practice. Bumped.

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
