### PR TITLE
Adds Bitrise Setup

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

Adds some configuration so that Bitrise will build the project correctly. 

### How do I test this PR?

Checkout the Bitrise project and confirm the app is building

image

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [DEV-XXX](#url)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set two relevant reviewers

## REVIEW

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@IsaacHardy Can you review and approve this? It's building fine for both iOS and Android now. You'll need to setup the Play/Console integrations, or I can do that if you don't have time.

**Review by IsaacHardy — COMMENTED** [review]
@vinnyjth Should we also delete the `appcenter-pre-build.sh`?

**Comment by IsaacHardy** [comment]
@vinnyjth Also, to create a new build, we'd need to merge master into `deploy-ios` and `deploy-android`?

**Comment by vinnyjth** [comment]
> @vinnyjth Should we also delete the `appcenter-pre-build.sh`?

Sure

**Comment by vinnyjth** [comment]
> @vinnyjth Also, to create a new build, we'd need to merge master into `deploy-ios` and `deploy-android`?

As soon as you merge this, I will setup auto builds when a new PR is merged into master.

**Pull request closed without merging**
