### PR TITLE
[DEV-4028] Hide Pass in Production

### PR DESCRIPTION
**Pull request by cdanwards**
### What does this PR do, or why is it needed?

This PR hides the pass on the connect page in production.

### How do I test this PR?

You can specify the logic like so to test in development:
```
process.env.NODE_ENV !== 'development'
```

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
we need to hide the action bar and put a link to giving in the table. it's gonna look goofy with only one button on it.

**Review by redreceipt — CHANGES_REQUESTED** [review]
left a comment

**Comment by richarddubay** [comment]
I agree with @redreceipt. No action bar on any environment and a link to give in the table. 👍

**Comment by redreceipt** [comment]
pretty sure `yarn.lock` shouldn't change here

**Pull request closed without merging**
