### PR TITLE
[DEV-3738] Adds New Prayer Icon

### PR DESCRIPTION
**Pull request by richarddubay**
### What does this PR do, or why is it needed?
This PR adds a new icon for the prayer feature to the navigation.

Screenshot 2019-09-15 16 15 45

### How do I test this PR?
Open up a sim for iOS and Android and make sure you can see the new icon.

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [x] Review updates to test coverage and snapshots
- [x] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [x] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
It's a little smaller than the others so the top and bottom don't line up right

**Review by redreceipt — DISMISSED** [review]
It's a little smaller than the others so the top and bottom don't line up right

**Comment by cdanwards** [comment]
@redreceipt So they're both `24 x 24`... as far as the alignment, I'm not sure.

**Review by cdanwards — APPROVED** [review]
Nice!

**Pull request merged**
