### PR TITLE
(DEV-3896) Adds Group Leader Link

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-09-26 at 4 20 17 PM

### What does this PR do, or why is it needed?

Adds group leader toolbox

### How do I test this PR?

click the link in the connect tab

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [ ] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
https://github.com/ApollosProject/apollos-prototype/issues/676

**Comment by redreceipt** [comment]
works :)

Screen Shot 2019-09-26 at 4 38 03 PM

**Comment by richarddubay** [comment]
Screenshot 2019-09-26 16 54 54

@redreceipt This has a back button AND a "X" like a modal. It comes up like a modal, but the "< Back" is the only thing that closes the window. The "X" doesn't work. I feel like if it's a modal, it should just be the "X", don't you?

**Comment by redreceipt** [comment]
Yea probably, that's an issue with the `UserWebBrowser`

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Review by richarddubay — APPROVED** [review]

**Pull request merged**
