### PR TITLE
[DEV-3838] Fixes Android crash when opening LocationFinder

### PR DESCRIPTION
**Pull request by cdanwards**
### What does this PR do, or why is it needed?

Currently, when in the onboarding LocationFinder or in the setting Locations view, it crashes on Android. Google Maps Platform recently required projects using the specifications that we use to include a reference to a legacy library, documentation [here](https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library).

Also, there is a duplicate reference to the `react-native-maps` library in the settings.gradle, so I removed it.

### How do I test this PR?

On Android, navigate to a mapview and ensure that the app doesn't crash.

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [ ] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
@cdanwards This works! 🎉

Just curious more than anything else ... is there any reason why we couldn't update to `com.google.android.gms:play-services-maps:16.1.0` instead of having to add the legacy library?

**Comment by cdanwards** [comment]
> @cdanwards This works! 🎉
> 
> Just curious more than anything else ... is there any reason why we couldn't update to `com.google.android.gms:play-services-maps:16.1.0` instead of having to add the legacy library?

@richarddubay I mean yeah, we could totally do that haha

**Comment by richarddubay** [comment]
I'm just saying, I'd rather go forward than back if we could. @IsaacHardy do you have an opinion?

**Comment by FrankGrand** [comment]
@richarddubay @cdanwards Unless @IsaacHardy has a reason not to update I agree that we might as well go forward instead of keeping old things going.  Does this change the scope of the task a large amount?

**Comment by IsaacHardy** [comment]
Agree with @richarddubay. Let's update to a newer version of the map sdk.

**Comment by cdanwards** [comment]
@richarddubay @IsaacHardy should be gtg now

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
