### PR TITLE
(DEV-3964) Enables Username Login

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

This ports the core changes for username login.

### How do I test this PR?

Try and login with a staff account

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
@redreceipt I feel like this should be pointing at `develop` and not `master`, right?

**Comment by redreceipt** [comment]
Haha yeah

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by richarddubay** [comment]
Screenshot 2019-09-03 17 01 37

@redreceipt So if it's not a full email address, the "Sign In" button does not become active. Does something else need to happen here so that this will work?

**Comment by richarddubay** [comment]
@redreceipt Also, the `yarn.lock` file changed after I ran `yarn`. Did you test this?

**Comment by redreceipt** [comment]
Yeah I forgot to change the hard coated value of the prop and I can't
remember if I ran test or not.

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Review by richarddubay — APPROVED** [review]
Looks like it works!

**Pull request merged**
