### PR TITLE
[DEV-3884] Refactors Prayer Header

### PR DESCRIPTION
**Pull request by cdanwards**
### What does this PR do, or why is it needed?

Part of the Rosary Refactor:

This updates the Avatar header to align with new design. Namely, changing it to no longer be align center.

### How do I test this PR?

Open up a sim an make sure that the avatar is not aligned center. Run tests.

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [ ] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
Would simply wrapping it in a padded view solve this instead?

**Review by richarddubay — COMMENTED** [review]
Make sure that you update the Storybook stories too.

**Comment by richarddubay** [comment]
> Make sure that you update the Storybook stories too.

FWIW, they may not need to be updated. They might just work. I haven't tested yet.

**Comment by cdanwards** [comment]
@redreceipt I did it this way for the specificity of the padding. I'd also have to style a PaddedView to match the mocks.

**Comment by redreceipt** [comment]
> @redreceipt I did it this way for the specificity of the padding. I'd also have to style a PaddedView to match the mocks.

I need you to teach me how to match the mocks

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
