### PR TITLE
Fixes Group Prayers Algorithm

### PR DESCRIPTION
**Pull request by redreceipt**
## TODO

- [ ] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [ ] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
@richarddubay so...I severely underestimated how complicated this would be server-side, it's turning into a lot of data calls. Groups calls aren't seeming to help that much because your endpoint is doing all the same stuff, just on the Rock side.

**Comment by richarddubay** [comment]
@redreceipt So, I went back and read through the task and the comments (https://newspring.atlassian.net/browse/DEV-3925). The problem we ran into was that when we added a prayer for Isaac, it was added using his `PrimaryAliasId`. But Frank wasn't seeing that prayer because Isaac's alias id in Frank's group was a different id than the `PrimaryAliasId`. 

What if the fix is just as easy as not doing `FirstOrDefault()` here?https://github.com/NewSpring/Rock/blob/master/Rock.Rest/Controllers/PrayerRequestsController.Partial.cs#L175

**Comment by redreceipt** [comment]
Give it a shot! Trying to do it on the API is just gonna be too slow.

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by redreceipt** [comment]
I'll leave this one open to preserve the work until we know the other way works

**Pull request closed without merging**
