### PR TITLE
Optimizes Saving Prayers

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Removes an unnecessary query and restructures code a little.

### How do I test this PR?

Save and unsave some prayers.

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
currently, saving prayers is broken on `develop`, should wait until it's resolved.

**Comment by richarddubay** [comment]
This is no longer blocked by saved prayers not working.

**Comment by richarddubay** [comment]
@redreceipt I don't want to presume to know how to fix these conflicts. If you fix them up, I can review this one.

**Comment by redreceipt** [comment]
resolved

**Comment by richarddubay** [comment]
Screenshot 2019-11-04 15 12 59

The prayers in my saved prayer list no longer show as saved. 

Also, once I close that list the entire app becomes unresponsive.

**Comment by redreceipt** [comment]
Well that’s no good :)

—
Michael

**Comment by redreceipt** [comment]
this one is ready

**Review by richarddubay — APPROVED** [review]

**Pull request merged**
