### PR TITLE
Updates project to use Apollos Core custom icon support

### PR DESCRIPTION
**Pull request by burkeshartsis**
## DESCRIPTION
This PR deprecates `NSIcon` in favor of the native Apollos Core custom icon support. Please review any additional code you may have copied over from Core that may no longer be needed for custom icon support. As far as I know, all unneeded code has been removed in this PR.
 
### What does this PR do, or why is it needed?
- Replaces all references to `NSIcon` with `Icon`
- Deletes any unnecessary code used to enabled use of `NSIcon`
- Renames references to `leaf-logo` to the Apollos Core standard naming of `brand-icon`. This simplifies and streamlines integration with the rest of Apollos Core.
### How do I test this PR?

Open app  and verify that all files changed are rendered as expected.

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by burkeshartsis** [comment]
Screenshots in order below right to left:
- Launch Screen
- NewSpring connect/login screen
- NewSpring SMS Auth
- NewSpring Onboarding
- NewSpring Prayer Module

**Comment by richarddubay** [comment]
@burkeshartsis I noticed there are a number of files that were removed from Onboarding. Did we just not know to remove them from our app when/if they were removed in core? I'm guessing those changes don't have anything to do with the icons, that's why I'm asking.

**Comment by richarddubay** [comment]
@cdanwards @IsaacHardy This seems good to me. Just waiting for Burke's answer regarding splash screen/onboarding stuff.

**Comment by burkeshartsis** [comment]
> I noticed there are a number of files that were removed from Onboarding. Did we just not know to remove them from our app when/if they were removed in core? I'm guessing those changes don't have anything to do with the icons, that's why I'm asking.

These deletions were completely unrelated to icon and when checking with @vinnyjth he said they were left over from when the upgrade tool didn't delete files on merge. I was touching most of the surface area of these files so I didn't think i twas a big deal to just delete these now.

**Review by richarddubay — APPROVED** [review]

**Pull request merged**
