### PR TITLE
Tweaks Some ContentSeriesContentItem Things

### PR DESCRIPTION
**Pull request by richarddubay**
### What does this PR do, or why is it needed?
This PR just tweaks a few of the items on the added `ContentSeriesContentItem` content type. Specifically:
* Doesn't let the background color fill the screen. In some of my testing the horizontal slider card color ended up looking almost exactly like the background color and it was hard to tell where the cards were.
* Moves the media content (video button) under the HTML content (title and description) so that it more closely matches what someone would see on the content items themselves. 

Screenshot 2019-11-15 16 08 14

### How do I test this PR?
Just look at some content series and see if you like how it looks.

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
This is entirely up to you all. 

Personally, I prefer the full-color overlay on content series (and actually did the same in the willow creek app). I would rather fix the horizontal content children appearance. This is also how your current app looks. I think it can be pretty slick if done right.

I also purposefully moved the video button to above the title for content series. Just because it's the series trailer and to help separate the image and the title a little bit, which say the same thing. I thought the hierarchy looked a little better, in this case. We can't do that on weekend content because of the pills above the title.

Again, this is all up to matter of opinion. @kevin-birdy might want to weigh in. He is working on some new styles for content children cards https://3.basecamp.com/3926363/buckets/6947926/todos/2207786858

**Comment by richarddubay** [comment]
@conrad-vanl I was just going for consistency across views. Felt kind of jarring to go from a full-color background (on the series) to not (on the item), but like I said in my Slack message, this was really just my personal preference. I do really like the full-color background but would almost like to see it everywhere if we were going to do that. 

FWIW, I want to wait and show off what you've done before we bother making changes.

**Comment by conrad-vanl** [comment]
I agree with both trains of thoughts @richarddubay !

I can have MIchael / @kevin-birdy look at it some next week.

**Comment by ridderingand** [comment]
On it 👍

**Pull request closed without merging**
