### PR TITLE
Adds Fill In The Blank Features

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Kapture 2019-07-16 at 22 09 01

### What does this PR do, or why is it needed?

Gives the ability to have fill in the blank answers to text features.

### How do I test this PR?

Go Live for Freedom series connected to production Rock API

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
blocked by #194

**Comment by richarddubay** [comment]
Hey @redreceipt and @cdanwards : How do you guys feel about reviewing this and getting it merged in to what we currently have? I know we're going to make some changes to it, but if we get it in then we can make sure that it is a part of the app when MM comes to check on it next week. I definitely want to be able to show him what we have currently so he can have a good idea of where we are.

**Comment by redreceipt** [comment]
yep no harm in that, I removed the features from production so we can demo them for him on alpha builds

**Review by cdanwards — APPROVED** [review]
This looks great!

**Pull request merged**
