### PR TITLE
(DEV-3958) Adds Series and Title to Notes

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-10-30 at 11 26 46 AM

### What does this PR do, or why is it needed?

Adds sermon and series titles to the sermon notes

### How do I test this PR?

Pull up some notes

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
I'm not seeing Series/Sermon/Speaker in the exported notes. Do you think they should be there? I kind of feel like they should be part of the deal, don't you?

**Comment by redreceipt** [comment]
Oh yes totally. I just forgot it. Good catch.

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by redreceipt** [comment]
ok @richarddubay check it now 

Screen Shot 2019-10-31 at 9 41 40 AM

**Comment by richarddubay** [comment]
Getting errors on "The Third Option" because `communicators` = `[null]` ... so it's trying to map over communicators even though it can't.

Screenshot 2019-10-31 12 15 06

**Comment by redreceipt** [comment]
got it 

Screen Shot 2019-11-02 at 9 19 51 PM

**Comment by richarddubay** [comment]
Made a couple issues in the backlog ([DEV-4204](https://newspring.atlassian.net/browse/DEV-4204) & [DEV-4205](https://newspring.atlassian.net/browse/DEV-4205)) for some things I saw ... but they shouldn't hold up this PR.

**Review by richarddubay — APPROVED** [review]

**Pull request merged**
